version: "3.9"

networks:
  c5net:
    driver: bridge

volumes:
  postgres_master_data:
  postgres_replica_data:
  redis_data:
  mosquitto_data:

services:

  
  # INFRAESTRUCTURA BASE
  

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: c5_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    networks:
      - c5net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: c5_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - c5net
    restart: unless-stopped

  postgres_master:
    image: postgres:15
    container_name: c5_postgres_master
    environment:
      POSTGRES_USER: c5admin
      POSTGRES_PASSWORD: c5secret
      POSTGRES_DB: c5db
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replicasecret
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./postgres/master-init.sh:/docker-entrypoint-initdb.d/master-init.sh
    ports:
      - "5432:5432"
    networks:
      - c5net
    restart: unless-stopped

  postgres_replica:
    image: postgres:15
    container_name: c5_postgres_replica
    environment:
      POSTGRES_USER: c5admin
      POSTGRES_PASSWORD: c5secret
      PGPASSWORD: replicasecret
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
      - ./postgres/replica-init.sh:/docker-entrypoint-initdb.d/replica-init.sh
    depends_on:
      - postgres_master
    ports:
      - "5433:5432"
    networks:
      - c5net
    restart: unless-stopped

  
  # MICROSERVICIO 1: RECEPCIÓN DE ALERTAS (x3 instancias)


  reception_1:
    build: ./services/reception
    container_name: c5_reception_1
    environment:
      - PORT=3001
      - INSTANCE_ID=reception_1
      - MQTT_BROKER=mqtt://mosquitto:1883
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mosquitto
      - redis
    networks:
      - c5net
    restart: unless-stopped

  reception_2:
    build: ./services/reception
    container_name: c5_reception_2
    environment:
      - PORT=3001
      - INSTANCE_ID=reception_2
      - MQTT_BROKER=mqtt://mosquitto:1883
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mosquitto
      - redis
    networks:
      - c5net
    restart: unless-stopped

  reception_3:
    build: ./services/reception
    container_name: c5_reception_3
    environment:
      - PORT=3001
      - INSTANCE_ID=reception_3
      - MQTT_BROKER=mqtt://mosquitto:1883
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mosquitto
      - redis
    networks:
      - c5net
    restart: unless-stopped

  
  # NGINX: Balanceador de carga (least_conn)
  

  nginx:
    image: nginx:alpine
    container_name: c5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - reception_1
      - reception_2
      - reception_3
    networks:
      - c5net
    restart: unless-stopped

  
  # MICROSERVICIO 3: ASIGNACIÓN DE PRIORIDAD (gRPC + HTTP)
  # Debe arrancar ANTES que Geolocation porque es el servidor gRPC
  

  priority:
    build: ./services/priority
    container_name: c5_priority
    environment:
      - GRPC_PORT=50051
      - HTTP_PORT=3003
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./services/priority/rules.json:/app/rules.json
    depends_on:
      - redis
    ports:
      - "50051:50051"
      - "3003:3003"
    networks:
      - c5net
    restart: unless-stopped

  
  # MICROSERVICIO 2: GEOLOCALIZACIÓN
  # Cliente gRPC de Priority — debe arrancar después de Priority
  # Flujo: queue:alerts → [geo enrich] → gRPC ClassifyAlert
  #      → queue:notify + queue:history + queue:transcription_input


  geolocation:
    build: ./services/geolocation
    container_name: c5_geolocation
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - PRIORITY_GRPC=priority:50051
    depends_on:
      - redis
      - priority
    networks:
      - c5net
    restart: unless-stopped

  
  # MICROSERVICIO 4: NOTIFICACIONES (WebSocket)
   

  notifications:
    build: ./services/notifications
    container_name: c5_notifications
    environment:
      - PORT=3004
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "3004:3004"
    networks:
      - c5net
    restart: unless-stopped

  
  # MICROSERVICIO 5: HISTORIAL DE INCIDENTES
  

  history:
    build: ./services/history
    container_name: c5_history
    environment:
      - PORT=3005
      - DB_MASTER=postgres://c5admin:c5secret@postgres_master:5432/c5db
      - DB_REPLICA=postgres://c5admin:c5secret@postgres_replica:5432/c5db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres_master
      - postgres_replica
      - redis
    ports:
      - "3005:3005"
    networks:
      - c5net
    restart: unless-stopped

  

  transcription:
    build: ./services/transcription
    container_name: c5_transcription
    environment:
      - REDIS_URL=redis://redis:6379
      - CAM_AUDIO_URL=http://192.168.2.23:8080/audio.wav
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - c5net
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: c5_frontend
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./app.js:/usr/share/nginx/html/app.js:ro
    ports:
      - "8090:80"
    depends_on:
      - notifications
      - history
    networks:
      - c5net
    restart: unless-stopped