events {
    worker_connections 1024;
}

http {
    upstream reception_cluster {
        least_conn;
        server reception_1:3001;
        server reception_2:3001;
        server reception_3:3001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://reception_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Log para verificar balanceo
            access_log /var/log/nginx/access.log;
        }
    }
}
